### ISSUE TITLE
XSD key order affects game client's features

### ISSUE THREAD

**Issue by KYGAS** [vezel-dev/novadrop#147] opened 2024-07-02 05:49 UTC
The only documented case of this that we have is "Abnormality.xml"

1) Unpack the client-dc using regular Novadrop features
2) Edit the Abnormality schema so that the ID is not in the first position ( 3rd/4th/... I didn't go into detail to confirm to what detail it matters )
3) Pack the client-dc using regualr Novadrop features ( using the edited schema )
4) Run the game and get any abnormality with "debuff=true" ( or whatever flags debuffs ) to apply.
5) HP bar will not turn purple ( or whatever color is set in the color settings for HP bar for debuff )

**Comment by alexrp** [comment] 2024-07-14 05:26
> Edit the Abnormality schema so that the ID is not in the first position ( 3rd/4th/... I didn't go into detail to confirm to what detail it matters )

Can you clarify what you mean by this exactly?

If I move the `xsd:attribute` element for `id` in the schema around, it doesn't seem to affect anything. Same if I move the position of the `id` attribute on a random `Abnormal` node in the data sheet.

**Comment by alexrp** [comment] 2024-07-15 15:37
Closing since this bug was originally observed in 2022 and doesn't seem to reproduce anymore, per Discord.

**Closed by alexrp** 2024-07-15 15:37 UTC
Labels: state: incomplete, type: bug, area: formats
